### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by da3dsoul1** [squidowl/halloy#141]
Is there any way to run this program portable? For it to store the configs inside the exe folder on windows?

**Comment by tarkah** [comment]
Not currently, but support should be easy. Is there a standard way for one to invoke a program into "portable mode" on Windows? As in, a common environment variable or CLI flag?

**Comment by casperstorm** [comment]
@smakkerlak do you know anything about this on Windows?

**Comment by smakkerlak** [comment]
For a portable windows app i would just assume executable and config file in a folder. Just run as current user, nothing fancy going on. I don't think you are currently doing anything that would require privilege escalation so you could do the minimum effort of checking for a config local to the executable and move on to the default system location if nothing is found.

You could also look into a configuration hierarchy, where closest in scope means highest precedence, essentially overlaying conf elements. I'm not sure how much value an application like Halloy would gain from this, but it would be neato. Could be a lot of cross platform fiddling if there isn't an off the shelf fix.

I'll help test if you need it.

**Comment by Daeraxa** [comment]
There are a couple of solutions that I've seen for this, one of which I think is exactly what @smakkerlak is advocating.

The easiest is to literally just throw the `config.yaml` into the same directory as the binary, if Halloy sees it there then it prefers that over any other file and writes its other data to the same place.

Another method (just adding in terms of possibility rather than necessarily thinking it is the best idea) would be to have an environmental variable that controls the location manually. So for example you could have a variable `HALLOY_CONFIG` which allows you to manually control where Halloy would look to create or find its config and data. This isn't really great for portability though and certainly for Linux it would be better to just support XDG properly instead.

**Comment by tarkah** [comment]
I think side by side config to binary is the easiest approach 👍

I believe this should only be in scope for Windows. In the unix world this isn't as much of an issue or concern.

**Comment by Daeraxa** [comment]
> I believe this should only be in scope for Windows. In the unix world this isn't as much of an issue or concern.

Out of interest, why not? The code for it (I imagine) would be fairly universal in terms of the actual logic and I generally find it is easier to not have to handle exceptions to the rule in the long term.

**Comment by da3dsoul1** [comment]
Thank you so much!
