### ISSUE TITLE
Feature request: Add "Open this channel at startup" toggle to channel context menu

### ISSUE THREAD

**Issue by Mardeg** [squidowl/halloy#169]
This menu item could be added just above the "Leave channel" item, and would result in the channel being added to or removed from the config.yaml file where appropriate. A checkmark (ticked box) would show if the channel has already been added, and either an empty checkbox or no checkmark otherwise.

**Comment by casperstorm** [comment]
Early on we decided that we are 100% config based, so we treat `config.yaml` as readonly.
This has a lot of benefits, one of them being that we can spend more time on features which relates to chatting rather than settings UI and good UX. So for now editing the settings has to happen through `config.yaml` directly.

**Comment by tarkah** [comment]
To expand on this, it's not good practice to write to a configuration file on behalf of users. This gets messy real fast.

So we have to determine: do we want server / channel setup to happen in the config file (defined by user) or persisted in app state when setup via the UI. Since UI server / channel management isn't in scope, we've preferred a config based approach.
