### ISSUE TITLE
Ensure we have information about ourself when joining a server

### ISSUE THREAD

**Issue by casperstorm** [squidowl/halloy#25]
After joining a server, we should do a `WHOIS` on ourself to ensure we have the correct hostname, username and nickname.
This is important because using config nickname might be wrong if our user is using a ZNC, so we want to pull latest information about ourself initially to make sure our state is correct.

**Comment by casperstorm** [comment]
Seems like this issue is a little more complicated since: https://github.com/aatxe/irc/issues/125

**Comment by tarkah** [comment]
This was addressed in #35 with the following strategy:

- RPL_WELCOME is sent after connecting, we set nickname (first parameter) from here
- NICK commands received updated nickname

We only fallback to the `irc` crate nickname but it should effectively never be used since `RPL_WELCOME` is sent right away before user should be able to do anything
