### ISSUE TITLE
WHO being rate-limited

### ISSUE THREAD

**Issue by jtbx** [squidowl/halloy#293]
I repeatedly get the following message in my Halloy server console:
```
* End of /WHO list.
WHO This command could not be completed because it has been used recently, and is rate-limited.
```

Why does Halloy need to poll WHO so often? It's slowing down my connection.

**Comment by casperstorm** [comment]
We poll every 60 second but only if they don't support away notify. 
I'll make it configurable and increase it by default to 3-5 minutes.

**Comment by jtbx** [comment]
Thank you very much <3

**Comment by aeadio** [comment]
This issue is still appearing for Libera in the latest version of Halloy, 2024.12. `who_poll_interval` and `who_retry_interval` seem to be ignored. Snippet from config:

```
[servers.znc-libera]
server = "<redacted>.ts.net"
port = 6501
use_tls = false
username = "<redacted>/libera"
password = "<redacted>"
nickname = "<redacted>"
realname = "<redacted>"
who_poll_interval = 3600
who_retry_interval = 3600
```

I get spammed with rate-limited messages regardless of which value is provided to those tunables. In fact, the rate limiting seems to be so bad, I can't do anything on Libera after startup -- like join additional channels or send messages.

I'm not interested in seeing who is away, so it's bizarre to me that this feature is not configurable.

**Comment by andymandias** [comment]
ZNC [supports away-notify](https://ircv3.net/software/clients), so you shouldn't be seeing continued WHO spam.  There will be a burst when launching Halloy, but that should be it.  Would you please open a new issue with your ZNC version and enabled modules @aeadio, so I can try to reproduce the issue.
