### ISSUE TITLE
[feature request] Homebrew Cask

### ISSUE THREAD

**Issue by vtu-dog** [squidowl/halloy#297]
First off, thank you for all this amazing work! Halloy single-handedly rekindled my love for IRC :)

It would be great to be able to install and manage Halloy via [Homebrew](https://brew.sh). I can already use it just fine by leveraging nixpkgs, but a cask with an .app bundle would be a huge step up for most macOS users - myself included, since managing GUI apps through nix is a subpar experience.

**Comment by casperstorm** [comment]
I would love to support `brew` but the right now we fail their first [requirement](https://docs.brew.sh/Acceptable-Casks#rejected-casks).

> App fails with GateKeeper enabled on Homebrew supported macOS versions and platforms (e.g. unsigned apps fail on Macs with Apple Silicon/ARM).

In order to sign it, we need to pay Apple $99 USD a year, so i've been postponing this a little until we have been closer to feature complete. I think we are close however, seeing as file transfers are landing soon (#292).

**Comment by casperstorm** [comment]
@vtu-dog the next release will be signed because we merged https://github.com/squidowl/halloy/pull/302, and once it releases (later this week) ill submit a brew request.

**Comment by casperstorm** [comment]
It has now been added to brew: https://formulae.brew.sh/cask/halloy.
```sh
brew install --cask halloy
```

**Comment by kapral18** [comment]
@casperstorm 
![image](https://github.com/squidowl/halloy/assets/1625373/50218805-bed2-4017-8f0d-c33a1843cbf8)

**Comment by kapral18** [comment]
@casperstorm my bad thanks
