### ISSUE TITLE
Banner on website

### ISSUE THREAD

**Issue by YouFoundAlpha** [squidowl/halloy#356]
It looks like the banner did not update from the PR I made yesterday #353 
Does anybody know why it didn't update after the PR was merged by Casper?

**Comment by casperstorm** [comment]
It isn't updated because it hasn't been deployed.
We deploy the book with every new release. If we deploy now, the book would have information about features not yet available in current latest build, and could confuse people.

So all is good, it will be updated once we release a new version of Halloy.

**Comment by YouFoundAlpha** [comment]
> It isn't updated because it hasn't been deployed. We deploy the book with every new release. If we deploy now, the book would have information about features not yet available in current latest build, and could confuse people.
> 
> So all is good, it will be updated once we release a new version of Halloy.

Ok
