### ISSUE TITLE
Graphical way to configure settings within Halloy

### ISSUE THREAD

**Issue by mlntr** [squidowl/halloy#386]
It should be possible to set the config inside the application's UI. This would be much better for discoverability and convenience.

Not everyone will be comfortable or expect the config to be a separate toml file to manually edit, and need to read documentation to figure when it should be intuitive for a simple GUI chat app.

**Comment by casperstorm** [comment]
Halloy will continue to only use `config.toml` for configuration. We prefer to add new features rather than create a complex settings UI, as everything can be done within the configuration file. Additionally, we put a lot of effort into keeping our wiki (https://halloy.squidowl.org/) up to date, which contains all the information needed.

For those who are not comfortable editing a config file, there are many other great IRC clients, which is why IRC is so great.
