### ISSUE TITLE
Scroll to bottom when pane gets focused

### ISSUE THREAD

**Issue by casperstorm** [squidowl/halloy#4]
Related to https://github.com/casperstorm/halloy/issues/3.
When a pane is focused, we should make sure to scroll to bottom.

**Comment by tarkah** [comment]
With #10, the buffer is always scrolled to the bottom as new messages come in, even if it's not focused. This seems like desirable behavior for any open buffer since the user can monitor them all at the same time. So this isn't really an issue currently.

However, I think we need to track when the user manually scrolls the scrollable. When they do, we should disable auto-snapping to bottom until they either:

- Scroll back to the bottom
- Click some indicator to snap back to bottom

But I don't think the actual interaction of focusing a buffer should ever trigger it. I think we're safe to close this and open a new ticket for tracking the users interaction on the scrollable as described above.
