### ISSUE TITLE
please  specify if the license is `GPL-3.0-only` or `GPL-3.0-or-later`

### ISSUE THREAD

**Issue by solomoncyj** [squidowl/halloy#460]

**Comment by KaiKorla** [comment]
IMO nothing to clarify. Read https://github.com/squidowl/halloy/blob/d76525fadb9c01bdabfd0b14c47dd20a45da2a54/LICENSE#L637C4-L640C40

regards

**Comment by LecrisUT** [comment]
Hi, Fedora packager here, let me clarify the issue here. In both `GPL-3.0-only` and `GPL-3.0-or-later`, the text of the license is identical and both include the clause that `or any later version`. What projects usually do is clarify in the README, or in the case of rust and SPDX license, they clarify by choosing explicitly `GPL-3.0-only`/`GPL-3.0-or-later`.

For reference, see the linux [GPL2.0 license text](https://github.com/torvalds/linux/blob/master/LICENSES/preferred/GPL-2.0) and the explicit clarification of `GPL-2.0-only` in the [COPYING](https://github.com/torvalds/linux/blob/master/COPYING) file.

Another note from a fellow packager:  `license` must point to a valid SPDX license tag, and *only* if you use a custom license not covered by SPDX, only then you can point it to a file using `license-file` [^1]
https://github.com/squidowl/halloy/blob/577c9f5471b5cc0b8166c340aab384e8cd796ab5/Cargo.toml#L7

[^1]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

**Comment by KaiKorla** [comment]
Hi @LecrisUT,

thank you for your hints. I understood the original bug report differently. PR is open.

regards
Kai

**Comment by casperstorm** [comment]
Merged. Thanks both.

**Comment by LecrisUT** [comment]
Thanks for the quick fix :slightly_smiling_face:
