### ISSUE TITLE
Failed to auto-join OFTC channels that require nick_password

### ISSUE THREAD

**Issue by o-alquimista** [squidowl/halloy#465]
I'm on 2024.9, which is supposed to contain #346 `Handle ERR_NEEDREGGEDNICK (aka ERR_NOCHANMODES)`. Yet, at least on OFTC, it's not working.

```
#tor-relays Cannot join channel (Need to be identified and verified to join this channel, '/msg NickServ help' to learn how to register and verify.)
```

```
[servers.oftc]
nickname = "removed"
nick_password = "removed"
nick_identify_syntax = "password-nick"
server = "irc.oftc.net"
channels = ["#tor-relays"]
```

I see the PR was only tested on Libera. As I use SASL to identify myself there, I did not test it.

___
EDIT 1:
~I would also propose to let us opt-in (in config.toml) to "delayed join" (`nick_identify_first`) - only ever join after nickserv identified - for a specific server. I don't mind delaying it for all the other channels.~

___
EDIT 2:
I've switched to [SASL (External)](https://www.oftc.net/NickServ/CertFP/), with which auto-join works as expected.

**Comment by andymandias** [comment]
OFTC doesn't send `RPL_LOGGEDIN` after a user logs in, so Halloy never recognizes itself as identified.  Potentially we can catch this by monitoring modes applied to the user, but it looks like that's not standardized across servers.  I think it might be best to go straight to IRCv3 `account-notify`, since that appears to be fairly widely adopted.  Then maybe fall back to looking for `+r` or `+R` user mode after that.

**Comment by andymandias** [comment]
I think I accidentally linked this to the PR which was a only halfway towards fully fixing this.  Second half is coming.
