### ISSUE TITLE
gruvbox theme screenshot is not helpful

### ISSUE THREAD

**Issue by dmd** [squidowl/halloy#520]
The [theme screenshot in the docs](https://halloy.squidowl.org/configuration/themes/community.html#gruvbox---save) for Gruvbox:

![image](https://github.com/user-attachments/assets/20964ebd-fc35-4601-bac4-b3381ce5fdf4)
is not helpful, as it's almost entirely server messages, not showcasing the actual color choices for the theme.

**Comment by casperstorm** [comment]
This is the old theme, provided by the community.
The new gruv box, which you find here: https://unstable.halloy.squidowl.org/configuration/themes/community#gruvbox---save looks like this:

![image](https://github.com/user-attachments/assets/c0bb62d0-4457-4391-b6a2-a90a6093dc57)

I'll close this issue since above theme is no longer available once we make a new release.
