### ISSUE TITLE
Parts not shown if we kill the application

### ISSUE THREAD

**Issue by casperstorm** [squidowl/halloy#73]
If a user kills the application, or connection, we don't see the `{user} has left the channel`

**Comment by ineeee** [comment]
this makes sense because the client never sends a `PART` or `QUIT` to the server

**Comment by tarkah** [comment]
What's the expected behavior here? Does IRC mandate a client sends QUIT before exiting? I'd imagine the server will broadcast part / quit when the client loses connection to the server.

I'd imagine we only want to implement this if we add a configuration where user can specify a QUIT / PART message when exiting the application / leaving channels.

**Comment by ineeee** [comment]
the client doesn't/can't determine the quit message because the process is already dead by that point, so its up to the irc daemon.

**Comment by tarkah** [comment]
> the client doesn't/can't determine the quit message because the process is already dead by that point, so its up to the irc daemon.

We actually capture the request to close the application and do some housecleaning... (flush history to disk, etc). So in theory we could send a QUIT from our client w/ a configurable message, if desired. This obv doesn't work if someone kills the running process vs graceful close.

**Comment by tarkah** [comment]
I'd imagine though that we should never send PART and only send QUIT as that is effectively a superset of PART. QUIT inherently means they have parted from all channels. 

So I think the scope of this issue should be:

- Send QUIT when user closes the application. Allow for configuring the QUIT message otherwise it sends an empty reason.

**Comment by casperstorm** [comment]
Fixed by #109.
Opened https://github.com/squidowl/halloy/issues/110 which continues the above discussion.
